#simple IOS config in ansible
---
- name: Sample IOS show version for Ansible 2.5
  hosts: Cisco_IOS
  gather_facts: false

  vars_prompt:
    - 
        name: username
        prompt: Junos Username
        private: false

    - 
        name: password
        prompt: Junos Password
        private: true

  tasks:

    - name: GATHERING FACTS
      ios_facts:
      gather_subset: hardware
    
      provider:
        hosts: "{{ ansible_host }}"
        user: '{{ username }}'
        passwd: '{{ password }}'

    - name: display current IOS version
      debug:
        var: ansible_net_version

    - name: run show ip int brie
      ios_command:
        commands: show ip interface brief
        register: myint

    - name: display value of "myint" variable
      debug:
        var: myint["stdout_lines"][0]

## Lab 1
    - name: run show users
      ios_command:
        commands: show users
        register: shuser

    - name: display value of "shuser" variable
      debug:
        var: shuser["stdout_lines"][0]
