---
- name: Checking Internet links
  hosts: 
    - Juniper_device
  collections:
    - juniper.device
  connection: local
  gather_facts: yes

  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no
    - name: password
      prompt: Junos Password
      private: yes

  tasks:
    - name: "Get the route on ED's router"
      rpc:
        host: "{{ ansible_host }}"
        port: 22
        user: "{{ username }}"
        passwd: "{{ password }}"
        rpcs:
          - "get-route-information"
      register: route
    
    - name: Display route
      debug:
        var: route.parsed_output